######################################################################
# Automatically generated by qmake (3.0) Thu Sep 29 10:34:51 2016
######################################################################

QT += bluetooth

CONFIG += debug

TEMPLATE = app
TARGET = ankioverdrive
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    bluetoothcontroller.cpp \
    racecar.cpp

HEADERS += \
    bluetoothcontroller.h \
    racecar.h
